projects:
  csc47300project:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 7uxsnls34rfefil3q6mbazstwa
      endpoints:
        prod: >-
          https://ctvvvva7ora3dolwrihfqdslh4.appsync-api.us-east-1.amazonaws.com/graphql
